---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodejs-app1
  namespace: default
  labels:
    app: nodejs-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app1
  template:
    metadata:
      labels:
        app: nodejs-app1
    spec:
      containers:
      - name: nodejs-app1
        image: "good777lord/node-app1:latest"
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app1
  namespace: default
spec:
  selector:
    app: nodejs-app1
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 3000
    port: 80
